In [1]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password=""
)

if conn.is_connected():
    print("Connected to MySQL successfully!")

conn.close()

Connected to MySQL successfully!

In [2]:
import mysql.connector

# Establish Database Connection
conn = mysql.connector.connect(
    host="localhost",
    user="root",  # Change to your MySQL username
    password="",  # Change to your MySQL password
)

# Create cursor object to interact with MySQL
cursor = conn.cursor()

# Create Database
cursor.execute("CREATE DATABASE IF NOT EXISTS saidi_shariffu_lab")
cursor.execute("USE saidi_shariffu_lab")

# Table creation SQL statements
tables = {
    "user_roles": """
        CREATE TABLE IF NOT EXISTS user_roles (
            role_Id INT AUTO_INCREMENT PRIMARY KEY,
            role_name VARCHAR(255) NOT NULL
        )
    """,
    "users": """
        CREATE TABLE IF NOT EXISTS users (
            user_Id INT AUTO_INCREMENT PRIMARY KEY,
            fname VARCHAR(255) NOT NULL,
            lname VARCHAR(255) NOT NULL,
            username VARCHAR(255) NOT NULL,
            email VARCHAR(255) NOT NULL,
            phone VARCHAR(255) NOT NULL,
            password VARCHAR(255) NOT NULL,
            role_Id INT,
            status VARCHAR(255) NOT NULL DEFAULT 'Active',
            FOREIGN KEY (role_Id) REFERENCES user_roles(role_Id) ON DELETE SET NULL ON UPDATE CASCADE
        )
    """,
    "computers": """
        CREATE TABLE IF NOT EXISTS computers (
            computer_Id INT AUTO_INCREMENT PRIMARY KEY,
            computer_name VARCHAR(255) NOT NULL,
            status ENUM('Available', 'Reserved', 'UnderMaintenance') NOT NULL
        )
    """,
    "reservation": """
        CREATE TABLE IF NOT EXISTS reservation (
            reservation_Id INT AUTO_INCREMENT PRIMARY KEY,
            user_Id INT,
            computer_Id INT,
            reservation_date DATETIME NOT NULL,
            reservation_status ENUM('Active', 'Completed', 'Cancelled') NOT NULL,
            FOREIGN KEY (user_Id) REFERENCES users(user_Id) ON DELETE CASCADE ON UPDATE CASCADE,
            FOREIGN KEY (computer_Id) REFERENCES computers(computer_Id) ON DELETE CASCADE ON UPDATE CASCADE
        )
    """,
    "maintenance": """
        CREATE TABLE IF NOT EXISTS maintenance (
            maintenance_Id INT AUTO_INCREMENT PRIMARY KEY,
            maintenance_date DATETIME NOT NULL,
            computer_Id INT,
            description VARCHAR(255) NOT NULL,
            FOREIGN KEY (computer_Id) REFERENCES computers(computer_Id) ON DELETE CASCADE ON UPDATE CASCADE
        )
    """
}

# Execute table creation
for table_name, table_sql in tables.items():
    cursor.execute(table_sql)
    print(f"Table {table_name} created successfully.")

# Close connection
cursor.close()
conn.close()

print("Database setup complete.")

Table user_roles created successfully.
Table users created successfully.
Table computers created successfully.
Table reservation created successfully.
Table maintenance created successfully.
Database setup complete.

In [5]:
import mysql.connector

# Establish Database Connection
conn = mysql.connector.connect(
    host="localhost",
    user="root",  # Change to your MySQL username
    password="",  # Change to your MySQL password
    database="saidi_shariffu_lab"  # Use the specific database you've created
)

# Create cursor object to interact with MySQL
cursor = conn.cursor()

# Example 1: Retrieve all user roles
cursor.execute("SELECT * FROM user_roles")
user_roles = cursor.fetchall()  # Retrieve all rows from the query

print("User Roles:")
for role in user_roles:
    print(role)

# Example 2: Retrieve all users
cursor.execute("SELECT * FROM users")
users = cursor.fetchall()

print("\nUsers:")
for user in users:
    print(user)

# Example 3: Retrieve all computers
cursor.execute("SELECT * FROM computers")
computers = cursor.fetchall()

print("\nComputers:")
for computer in computers:
    print(computer)

# Example 4: Retrieve all reservations
cursor.execute("SELECT * FROM reservation")
reservations = cursor.fetchall()

print("\nReservations:")
for reservation in reservations:
    print(reservation)

# Example 5: Retrieve all maintenance records
cursor.execute("SELECT * FROM maintenance")
maintenances = cursor.fetchall()

print("\nMaintenance Records:")
for maintenance in maintenances:
    print(maintenance)

# Close the cursor and connection
cursor.close()
conn.close()

print("\nData retrieval complete.")

User Roles:

Users:

Computers:

Reservations:

Maintenance Records:

Data retrieval complete.

In [6]:
import mysql.connector

# Establish Database Connection
conn = mysql.connector.connect(
    host="localhost",
    user="root",  # Change to your MySQL username
    password="",  # Change to your MySQL password
    database="saidi_shariffu_lab"  # Use the specific database you've created
)

# Create cursor object to interact with MySQL
cursor = conn.cursor()

# Example 1: Update user's status
user_id_to_update = 1  # Specify the user_id you want to update
new_status = 'Inactive'  # The new status to set

cursor.execute("""
    UPDATE users
    SET status = %s
    WHERE user_Id = %s
""", (new_status, user_id_to_update))

print(f"Updated user with user_Id {user_id_to_update} status to {new_status}")

# Example 2: Update computer status
computer_id_to_update = 2  # Specify the computer_id you want to update
new_computer_status = 'Available'  # The new status to set

cursor.execute("""
    UPDATE computers
    SET status = %s
    WHERE computer_Id = %s
""", (new_computer_status, computer_id_to_update))

print(f"Updated computer with computer_Id {computer_id_to_update} status to {new_computer_status}")

# Example 3: Update reservation status
reservation_id_to_update = 1  # Specify the reservation_id you want to update
new_reservation_status = 'Completed'  # The new status to set

cursor.execute("""
    UPDATE reservation
    SET reservation_status = %s
    WHERE reservation_Id = %s
""", (new_reservation_status, reservation_id_to_update))

print(f"Updated reservation with reservation_Id {reservation_id_to_update} status to {new_reservation_status}")

# Commit the changes to the database
conn.commit()

# Close the cursor and connection
cursor.close()
conn.close()

print("\nData update complete.")

Updated user with user_Id 1 status to Inactive
Updated computer with computer_Id 2 status to Available
Updated reservation with reservation_Id 1 status to Completed

Data update complete.

In [7]:
import mysql.connector


conn = mysql.connector.connect(
    host="localhost",
    user="root",  
    password="",  
    database="saidi_shariffu_lab"  
)


cursor = conn.cursor()


user_id_to_delete = 1  

cursor.execute("""
    DELETE FROM users
    WHERE user_Id = %s
""", (user_id_to_delete,))

print(f"User with user_Id {user_id_to_delete} has been deleted.")


computer_id_to_delete = 2  

cursor.execute("""
    DELETE FROM computers
    WHERE computer_Id = %s
""", (computer_id_to_delete,))

print(f"Computer with computer_Id {computer_id_to_delete} has been deleted.")


reservation_id_to_delete = 1  

cursor.execute("""
    DELETE FROM reservation
    WHERE reservation_Id = %s
""", (reservation_id_to_delete,))

print(f"Reservation with reservation_Id {reservation_id_to_delete} has been deleted.")


conn.commit()


cursor.close()
conn.close()

print("\nData deletion complete.")

User with user_Id 1 has been deleted.
Computer with computer_Id 2 has been deleted.
Reservation with reservation_Id 1 has been deleted.

Data deletion complete.